### PR TITLE
Iss9 - Event Bus Re-Design

### LINKED ISSUE #3: Remove dependency on Event
Currently, Framework makes use of a couple of classes defined in the ldmx-sw/Event module.  These include 
* Event/EventDef.h
* Event/RunHeader.h
* Event/EventHeader.h

Some of these can be made generic enough that they can be moved to the Framework module.  However, removing the dependency on the EventBusPassenger is trickier. Whatever the case, for this to compile on it's own, the dependency on these classes will need to be removed.

### LINKED ISSUE #9: Clean Up Event class
The Event bus is taped together rather weakly and we should clean it up.

The following line is the main offender, in order for the passengers map to figure out the type of the object, we have to copy the object fully from the TTree to the map.
```cpp
passengers_[branchName] = *((T *)(branch->GetObject())); //this will fail if wrong type is passed
```

We don't know how to fix up this copy right now, but we can start by hiding it within a `Handle` templated class that holds the event bus passenger in it. This handle could be a replacement for `std::variant` that would hold the class as well as interface with the TTree in a more helpful way.

### LINKED ISSUE #30: Can't analyze 2 or more different pass names in one run
I discovered this when attempting to analyze several different signal style generators at once.

## Hypothesis
This is being caused by the branch names of the input-file branches being left defined with the previous input-file's pass name (no proof). 

## Solution
I still haven't solved this, but I also wanted to bring this up as something that we may not want to solve.... Are we okay with analyzing more than one different passes in a single run?
- If not, I can implement an exception so that the user knows why they are seeing this error.
- If yes, then I can figure out how to fix this up.

*Not Urgent*: very niche use case of the Framework.

### LINKED ISSUE #39: Add Total Reset for NtupleManager
This will only be helpful for writing tests which may or may not use the NtupleManager in multiple tests within the same library.

Error observed in https://github.com/LDMX-Software/Hcal/pull/5

Just need a `NtupleManager::reset` function which is called when `Process::run` starts.

### PR DESCRIPTION
**Pull request by tomeichlersmith**
With a rather fun inheritance tree and some fancy shmancy ["partial" template specialization](https://www.fluentcpp.com/2017/08/15/function-templates-partial-specialization-cpp/), we can ditch the use of `std::variant` and deep copies from our event bus design and use more references (only copying where we need to).

The heavy lifting is done by a new file `Bus.h` which defines a multi-level inheritance structure that allows us to handle passengers with the **only requirement** being that they are members of the ROOT dictionary (so that the TTree can serialize them). This inheritance structure has two levels, both of which should be hidden from all users outside of the `Bus` class itself which acts as the "bus" which "passengers" ride while carrying our "objects". Additionally, isolating the "bus" into its own class allows us to use the same buffering system in the NtupleManager, so now the NtupleManager can (technically) handle anything the core event bus can! (I'm assuming most will still focus on basic types and vectors of basic types.)

## Design Structure

I've tried to heavily document the new design in the `Bus` class, but here is the general idea. We start at the bottom of the tree and work our way up.

- `Seat`: This is the foundation of the bus. Each bus passenger (which does know the type of object it is carrying) is given a seat on the bus that doesn't know what the type of object is being carried. This allows the bus to have one container for all the different types of objects that will be carried and tell all of the objects to reset themselves at the end of the event.
- `Passenger` : This is the passenger on the bus and can do the core functions of (1) defining the type of "baggage" that the passenger is carrying (2) `attach` ing the baggage to a `TTree` (3) updating the contents of the baggage and (4) resetting ("clearing") the baggage to a default/empty state at the end of each event. Here I use a complicated mixture of template functions, full template specialization, and function overloading to make sure that the different types we want to be carried can be handled correctly. [The helpful blog post I linked above](https://www.fluentcpp.com/2017/08/15/function-templates-partial-specialization-cpp/) gave me the idea for how to do this.
- `Bus`: Finally, the class that is actually used outside of this file. The `Bus` is used as a member variable of `Event` to carry the objects that will be used in processing. `Event::add` and `Event::getObject` are where the `Bus` is used most frequently to board a new type of object onto the bus, update the contents of the object, and get a const reference to the object for later reading.

## Types This Design can Handle
- BSILFD (bool, short, int, long, float, double) a.k.a. the signed arithmetic types
- Any class that has the 'Clear' method defined (needs to be added to ROOT dictionary if you wish to use the `attach` functionality)
- `std::vector` of any class with `operator<` defined
- `std::map` with any key type with `operator<` defined and any value type

## Discussion Points
- If we touch all of our current event passengers by renaming 'Clear' to 'clear', we can slightly simplify the code of `Passenger` since both `std::vector` and `std::map` have a method named `clear`.
- If we want the Bus design to handle printing, the easiest way to get this to work is to add the requirement that the `operator<<` is defined for all event bus objects. This would also require us to touch (nearly) all of our current event bus objects, but then it would be very straightforward to define how each passenger is streamed to the output and therefore how the entire bus is streamed.
- Any other basic types we want to be able to handle? The structure is very flexible, so I am confident that I could handle _any_ class that is in the ROOT dictionary (ours or the one shipped with ROOT).

### CODE REVIEW

**Comment by tomeichlersmith** [comment]
@omar-moreno I believe this work would be use-able by HPS (and LCIO) with the only modification being overloading the `attach` method (for `Bus`, `Seat`, and `Passenger`) so that LCIO "TTrees" can be attached to the objects being carried on the bus,

**Comment by omar-moreno** [comment]
What do you mean by LCIO TTrees?

**Comment by tomeichlersmith** [comment]
So, ROOT TTrees keep a handle to an object its serializing so that it the serializer is always looking at the same position in memory (until you tell it otherwise). This is why the Bus has the `attach` method, so that we can connect ROOT's trees to our objects so that they can talk to each other. When reading an ROOT TTree from a file, our objects are written to by the TTree using this connection. When writing objects out, we write to the object and then the ROOT TTree serializes the object at that memory location into the output file.

I'm assuming that LCIO has a similar border between objects in memory and objects that are serialized. If LCIO needs access to the address of the object you want to serialize (or deserialize), overriding the `attach` method is where that should be done.

**Comment by omar-moreno** [comment]
OK Thanks.



On Tue, Jan 19, 2021 at 1:16 PM Tom Eichlersmith <notifications@github.com>
wrote:

> So, ROOT TTrees keep a handle to an object its serializing so that it the
> serializer is always looking at the same position in memory (until you tell
> it otherwise). This is why the Bus has the attach method, so that we can
> connect ROOT's trees to our objects so that they can talk to each other.
> When reading an ROOT TTree from a file, our objects are written to by the
> TTree using this connection. When writing objects out, we write to the
> object and then the ROOT TTree serializes the object at that memory
> location into the output file.
>
> I'm assuming that LCIO has a similar border between objects in memory and
> objects that are serialized. If LCIO needs access to the address of the
> object you want to serialize (or deserialize), overriding the attach
> method is where that should be done.
>
I'll look into it, but it's not clear if the above solution is compatible
with LCIO. In the short term, I'll just adapt to what is in the trunk since
I have a solution for that working.  Long term, If I can't adapt to your
updates, I'll just create a simpler bus that is LCIO specific.

**Pull request merged**
